### ISSUE TITLE
Very low quality of wallpapers

### ISSUE THREAD

**Issue by nnunurs** [Phantom12/Unsplash-Wallpaper-Windows#5]
I've noticed that the wallpapers are much worse quality than the source, so they look awful on my high-res monitor. Is it something with the settings, or it's just the app not downloading photos in full res? Also, I'm using my own collection and photos on Unsplash are higher resolution than needed.

**Comment by Phantom12** [comment]
Hi @miszek2000, I was actually frustrated by this issue myself (having a 4K monitor). The app is currently using [Unsplash Source](https://source.unsplash.com/) simple API. It specifies the desirable image resolution (by default your monitor resolution) and the Unsplash server handles cropping. Choose [a random 4K image](https://source.unsplash.com/random/3840x2160), observe the redirected link and you will notice that Unsplash uses entropy crop. I believe the [entropy crop](https://docs.imgix.com/apis/rendering/size/crop) is the culprit of the low res image, especially since these days a lot of photos on Unsplash are of portrait orientation. 

A fix I have found is to use a curated desktop wallpaper collection as the image source. Personally, I'm currently using [Wallpapers for macOS Collection](https://unsplash.com/collections/7282015). Simply set `sourceURL=https://source.unsplash.com/collection/7282015/` in 

> %LocalAppData%\Unsplash_GUI\config.ini

Hope this helps.

.

**Comment by nnunurs** [comment]
Thank you for your quick answer. I managed to make it work, but I had some difficulties with applying the settings specified in config.ini. It worked when I closed the app completely, modified config, then lunched the app again. For some reason it doesn't work when you change the order and modified settings while the app is running and then restart.

Anyways, thanks for your help, it works now!
